import imageSrc from '../assets/card.jpg'
export const cards = [
    {
      image: imageSrc,
      title: '3 Days Trekking Expedition',
      date: '30 May',
      location: 'Delhi',
      // price: '₹9,999 - onwards',
      price: 200,
      tag: 'Outdoor',
    },
    {
      image: imageSrc,
      title: 'Sunburn Arena Ft. Alan Walker',
      date: 'Fri, 27 Sep',
      location: 'Kolkata',
      // price: 'Free',
      price: 80,
      tag: 'Concerts',
    },
    {
      image: imageSrc,
      title: 'Allen Solly Men Solid Polo Neck Cotton',
      date: '',
      location: '',
      // price: '₹714 (50% off)',
      price: 900,
      tag: 'Fashion',
    },
    {
        image: imageSrc,
        title: '3 Days Trekking Expedition',
        date: '30 May',
        location: 'Delhi',
        // price: '₹9,999 - onwards',
        price: 200,
        tag: 'Outdoor',
      },
      {
        image: imageSrc,
        title: 'Sunburn Arena Ft. Alan Walker',
        date: 'Fri, 27 Sep',
        location: 'Kolkata',
        // price: 'Free',
        price: 80,
        tag: 'Concerts',
      },
      {
        image: imageSrc,
        title: 'Allen Solly Men Solid Polo Neck Cotton',
        date: '',
        location: '',
        // price: '₹714 (50% off)',
        price: 900,
        tag: 'Fashion',
      },
      {
        image: imageSrc,
        title: '3 Days Trekking Expedition',
        date: '30 May',
        location: 'Delhi',
        // price: '₹9,999 - onwards',
        price: 200,
        tag: 'Outdoor',
      },
      {
        image: imageSrc,
        title: 'Sunburn Arena Ft. Alan Walker',
        date: 'Fri, 27 Sep',
        location: 'Kolkata',
        // price: 'Free',
        price: 80,
        tag: 'Concerts',
      },
      {
        image: imageSrc,
        title: 'Allen Solly Men Solid Polo Neck Cotton',
        date: '',
        location: '',
        // price: '₹714 (50% off)',
        price: 900,
        tag: 'Fashion',
      },
  ];